# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: YouthOnTheMove
title-icon: "fa-solid fa-plane-departure"
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Le site <a href='/'>YouthOnTheMove</a> est un projet mené par <a href='https://www.inforjeuneswaterloo.be'>l'ASBL Infor Jeunes Waterloo</a> qui est un 
  Centre d'Information Jeunesse agréé et subventionné par la <a href='http://www.cfwb.be' target='_blank'>Fédération Wallonie-Bruxelles</a>
  et soutenu par l'Echevinat de la jeunesse de la ville de <a href='https://www.waterloo.be'>Waterloo</a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Pagination

pagination:
  enabled: true             # Enable the pagination generator
  per_page: 3             # Number of items per page (default: 10)
  permalink: '/page/:num/' # Permalink structure for pagination pages
                           # :num will be replaced by the page number
  title: ':title - Page :num of :max' # Optional: Format for the title of paginated pages
                           # :title - original page title
                           # :num - current page number
                           # :max - total number of pages
  limit: 0                  # Optional: Limit the total number of pagination pages to generate (0 for all)
  sort_field: 'date'        # Field to sort items by (default: date)
  sort_reverse: true        # Reverse the sort order (default: false)
  collection: 'posts'       # Default collection to paginate if not specified in page front matter

# Build settings
permalink: /:title/
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
