name: Jekyll Deploy

on:
  push:
    branches:
      - master # Or your default branch

jobs:
  jekyll-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.3' # Or the Ruby version you use

      - name: Cache Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle config set --local path vendor/bundle
          bundle config set --local without 'development test' # Optional: Speed up install
          bundle install --jobs 4 --retry 3

      - name: Build with Jekyll
        run: bundle exec jekyll build --trace

      - name: Upload Artifact
        uses: actions/upload-artifact@<a specific commit SHA>
        with:
          name: jekyll-site
          path: _site

  deploy:
    needs: jekyll-build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4  
        with:
          folder: _site
          branch: gh-pages